version: "3.7"

services:
  db:
    image: postgres:16
    container_name: crm_db
    env_file:
      - .env-non-dev
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
#    restart: always

  crm_finance:
    image: crm_finance_image
    build:
      context: .
    container_name: crm_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
    ports:
      - "9000:8000"
#    restart: always
    command: >
      sh -c "alembic upgrade head && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"

volumes:
  postgresdata:
