version: "3.7"

services:
  db:
    image: postgres:16
    container_name: crm_db
    env_file:
      - .env-prod
    environment:
      - POSTGRES_DB=crm_system_db
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

  crm_finance:
    image: crm_image
    build:
      context: .
    container_name: crm_app
    env_file:
      - .env-prod
    depends_on:
      - db
    command: >
       sh -c "alembic upgrade head && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 9000:8000

volumes:
  postgresdata:
